.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. namecoin_qt test_namecoin_qt
clean: FORCE
	$(MAKE) -C .. namecoin_qt_clean test_namecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_namecoin_qt_check
namecoin-qt namecoin-qt.exe: FORCE
	 $(MAKE) -C .. namecoin_qt
