.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. xaya_qt test_xaya_qt
clean: FORCE
	$(MAKE) -C .. xaya_qt_clean test_xaya_qt_clean
check: FORCE
	$(MAKE) -C .. test_xaya_qt_check
xaya-qt xaya-qt.exe: FORCE
	 $(MAKE) -C .. xaya_qt
apk: FORCE
	$(MAKE) -C .. xaya_qt_apk
